package io.ylab.task02.sequences;

public class SequencesTest {
    public static void main(String[] args) {
        Sequences sequences = new SequencesImpl();

        System.out.println("Sequence A.");
        System.out.println("N = -1:");
        sequences.a(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.a(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.a(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.a(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.a(10);
        System.out.println();
        System.out.println("N = 1073741824:");
        sequences.a(1073741824);
        System.out.println();

        System.out.println("Sequence B.");
        System.out.println("N = -1:");
        sequences.b(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.b(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.b(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.b(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.b(10);
        System.out.println();
        System.out.println("N = 1073741825:");
        sequences.b(1073741825);
        System.out.println();

        System.out.println("Sequence C.");
        System.out.println("N = -1:");
        sequences.c(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.c(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.c(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.c(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.c(10);
        System.out.println();
        System.out.println("N = 46341:");
        sequences.c(46341);
        System.out.println();

        System.out.println("Sequence D.");
        System.out.println("N = -1:");
        sequences.d(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.d(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.d(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.d(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.d(10);
        System.out.println();
        System.out.println("N = 1291:");
        sequences.d(1291);
        System.out.println();

        System.out.println("Sequence E:");
        System.out.println("N = -1:");
        sequences.e(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.e(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.e(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.e(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.e(10);
        System.out.println();

        System.out.println("Sequence F:");
        System.out.println("N = -1:");
        sequences.f(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.f(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.f(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.f(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.f(10);
        System.out.println();

        System.out.println("Sequence G:");
        System.out.println("N = -1:");
        sequences.g(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.g(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.g(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.g(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.g(10);
        System.out.println();
        System.out.println("N = 46341:");
        sequences.g(46341);
        System.out.println();

        System.out.println("Sequence H:");
        System.out.println("N = -1:");
        sequences.h(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.h(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.h(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.h(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.h(10);
        System.out.println();

        System.out.println("Sequence I:");
        System.out.println("N = -1:");
        sequences.i(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.i(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.i(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.i(2);
        System.out.println();
        System.out.println("N = 12:");
        sequences.i(12);
        System.out.println();
        System.out.println("N = 13:");
        sequences.i(13);
        System.out.println();

        System.out.println("Sequence J:");
        System.out.println("N = -1:");
        sequences.j(-1);
        System.out.println();
        System.out.println("N = 0:");
        sequences.j(0);
        System.out.println();
        System.out.println("N = 1:");
        sequences.j(1);
        System.out.println();
        System.out.println("N = 2:");
        sequences.j(2);
        System.out.println();
        System.out.println("N = 10:");
        sequences.j(10);
        System.out.println();
        System.out.println("N = 46:");
        sequences.j(46);
        System.out.println();
        System.out.println("N = 47:");
        sequences.j(47);
        System.out.println();
    }
}
